name: "Release"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      RELEASE_TAG:
        description: 'version v{Major}.{Minor}.{Patch}'  

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          submodules: true

      # - name: Git submodule update
      #   run: |
      #     git submodule update --init
      
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: "${{ inputs.RELEASE_TAG }}",
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: "${{ inputs.RELEASE_TAG }}",
              });

            } catch (error) {
              core.setFailed(error.message);
            }